# Generated by Django 4.1.6 on 2023-04-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_photo_options_photo_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='user_photos', verbose_name='Фотография'),
        ),
    ]
