# Generated by Django 4.1.6 on 2023-03-15 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("webapp", "0005_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="users",
            field=models.ManyToManyField(
                related_name="articles",
                through="webapp.Favorite",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
